### ISSUE TITLE
Component override is broken if the overridden component does not have the same theme states as the overriding one

### ISSUE THREAD

**Issue by gbdrummer** [ngnjs/chassis#3]
If we have this theme:

```css
anchor {
  @state initial {
    color: green;
  }
}

anchor-button {
  @state initial {
    background: green;
    color: white;
  }

  @state focus {
    outline: 0;
  }
}
```

Because `anchor-button` overrides `anchor`, a build-blocking error will be thrown because `anchor-button` has a `focus` state in its theme while `anchor` does not. The diffing algo should allow for non-shared states.
